@echo off

::------------------------------------------------------------------------------
::  FILENAME     CAP18_Run_Examples.bat 
::  SUBJECT      Process selected CAP18 input files
::------------------------------------------------------------------------------
::
::!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
::!! ATTENTION: THIS WINDOWS BATCH FILE MUST BE COPIED AND THEN MODIFIED   !!
::!!            IN ORDER TO PROCESS THE DESIRED CAP18 INPUT FILES.         !!
::!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
::
:: COMMENTS
::
:: CAP18_Run_Examples.bat serves as an example for creating your own bat 
:: file to process a group of CAP18 input data files.
::
:: The CAP18 program takes only a single input of filename for the input
:: data file.  As the CAP18 program can process only one file at a time, a
:: Windows Command (.bat) file must be used to process a group of CAP18
:: input data files.
::
:: Your own ".bat" file may contain between one command line and several 
:: hundred commmand lines, depending on the number of input data files
:: that you wish to processs.  Regardless of the count, the syntax for
:: each command line is always the same, simply: 
::
::     CAP18 filename
::
:: For the example command lines, the user keeps his example CAP18 input data
:: files in the folder:  "C:\CAP18\Examples".  He specifies the filenames as
:: absolute file specs, although the names could be specified in three
:: different ways: (1) Filename Only, (2) Relative File Spec, or (3) 
:: Absolute File Spec, as follows.
::
:: 1. Filename Only - The filename does not contain a drive letter or
::    folder specification.  Ex: "Example01.dat".  When a filename is specified
::    this way, the file must reside in the current directory.
::
:: 2. Relative File Spec - The filename includes only enough information to 
::    locate the file relative to the current directory (CD). If the current
::    directory is C:\MyExamples, then the data file could be specified as
::    "Examples\Example01.dat". To specify parent folder, the special name or
::    notation is two dots "..".  If a subfolder exists within
::    "C:\CAP18\Examples" named "Ernie", and the current directory is
::    "C:\CAP18\Examples\Ernie", then the data file could be specified as
::    "..\Example01.dat".
::
:: 3. Absolute File Spec - The filename is explicit and contains the complete
::    filename: drive letter, folder, and filename, for example: 
::    "C:\CAP18\Examples\Example01.dat".
::    
:: A possibility exists that the filename contains spaces.  To prevent these
:: spaces from causing problems, the name should be surrounded with double
:: quotes. This should be done as a matter of practice, for example:
:: "C:\CAP18\Examples\Example01.dat".
::
:: Output files generated by the CAP18 program will be created in the folder
:: where their corresponding input file(s) reside(s).
::
::---------------------------------------------------------------------------
::
:: EXAMPLE CODE
::
:: Begin CAP18 processing commands.
::
:: Edit the following CAP18 command lines, as needed (see explanation above), to
:: process the desired input data files.
::
CAP18 "C:\CAP18\Examples\Example01.dat" 
CAP18 "C:\CAP18\Examples\Example02.dat" 
CAP18 "C:\CAP18\Examples\Example03.dat" 
CAP18 "C:\CAP18\Examples\Example04.dat" 
CAP18 "C:\CAP18\Examples\Example05.dat" 
CAP18 "C:\CAP18\Examples\Example06.dat" 
CAP18 "C:\CAP18\Examples\Example07.dat" 
CAP18 "C:\CAP18\Examples\Example08.dat" 
CAP18 "C:\CAP18\Examples\Example09.dat" 
CAP18 "C:\CAP18\Examples\Example10.dat" 
CAP18 "C:\CAP18\Examples\Example11.dat" 
CAP18 "C:\CAP18\Examples\Example12.dat" 
::
:: End CAP18 processing commands.
::
:: The following PAUSE command allows the command window to remain open until 
:: a key is entered; otherwise the window would disappear.
::
PAUSE
